### ISSUE TITLE
Any way to preserve monotonicity (and hence not hurt AUC) ?

### ISSUE THREAD

**Issue by pchalasani** [kartikgupta-at-anu/spline-calibration#2]
I have a simple binary classification scenario with probability scores. I find that the calibration drops AUC from 0.778 to 0.664, using 6 knots for the spline.
There are several violations of monotonicity.

In general is there a way to preserve monotonicity so that the AUC is not affected?

Please see the attached example csv file.
[score_calib.csv](https://github.com/kartikgupta-at-anu/spline-calibration/files/6760683/score_calib.csv)

**Comment by pchalasani** [comment]
To be clear, when I fitted the calibrator on a separate dataset, the AUC was maintained. My comment was about what happened when I applied the calibrator to the test dataset.

**Comment by kartikgupta-at-anu** [comment]
Its not fully clear to me why AUC drops here but maybe for binary classification case a simple temperature scaling would be able to do good job at calibration if you want to preserve the decision. Since spline based calibration in this paper works on top-1, top-2 etc , it is possible that calibrator changes the decision sometimes but as shown in the paper it happens rarely and thus accuracy is mostly preserved after calibration.
